name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Install esptool
        run: |
          pip install -U esptool

      - name: Create Cardputer Firmware Binary
        run: |
          esptool.py --chip esp32s3 merge_bin --output Remote.bin \
            0x00000 .pio/build/m5cardputer/bootloader.bin \
            0x08000 .pio/build/m5cardputer/partitions.bin \
            0x10000 .pio/build/m5cardputer/firmware.bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: CardputerRemote
          path: Remote.bin
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    environment: github_release
    needs: [build]
    if: github.ref_type == 'tag'

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: CardputerRemote

    - name: Show directory structure
      run: tree

    - name: Release ${{ github.ref_name }}
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
        files: Remote.bin
